// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emwjnjqmyzuzuuwglwxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtd2puanFteXp1enV1d2dsd3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTMxOTksImV4cCI6MjA3MjY2OTE5OX0.3gY1vpHAqACM2A3hLJ1yjG_Mgy--INM2ABnBwsEwIBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});